name: magicDog Actions
on:
  label:
    types:
      - created
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest , windows-11-arm ]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
#    container:
#      image: docker.1ms.run/catthehacker/ubuntu:act-22.04
#      volumes:
#        - ubuntu_hostedtoolcache:/opt/hostedtoolcache
    steps:
      - run: echo "🍎 当前时间" & date
      - uses: actions/checkout@v5

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          architecture: 'aarch64'
          cache: 'gradle'

      - name: Build native image
        uses: gradle/actions/setup-gradle@v3
        with:
          job-id: jdk21
          arguments: nativeCompile
          gradle-version: wrapper

      - name: Make staging directory
        run: mkdir staging

      - name: Copy native bundles to staging
        run: |
          cp -r modules\server\build\native\nativeCompile\* staging
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Server-Windows
          path: staging
          retention-days: 1
